# Uncomment the next line to define a global platform for your project
  platform :ios, '14.0'

target 'YoutubeaApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YoutubeaApp
  pod 'Alamofire'
  pod 'GoogleSignIn', '~> 5.0.2'
end
